# Generated by Django 3.0.6 on 2020-05-23 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата')),
                ('name_task', models.CharField(max_length=200, verbose_name='Название задачи')),
                ('discription_task', tinymce.models.HTMLField(verbose_name='Описание задачи')),
                ('result', models.CharField(max_length=200, null=True, verbose_name='Результат')),
                ('count_answer', models.IntegerField(default=0, verbose_name='Количество человек, которые могут решить задачу (указать отрицательное число)')),
                ('id_answers', models.CharField(blank=True, default='', max_length=200, verbose_name='ID учеников, кто дал правильный ответ')),
            ],
            options={
                'verbose_name': 'Задача дня',
                'verbose_name_plural': 'Задача дня',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата')),
                ('theme', models.CharField(default='', max_length=200, verbose_name='Название темы')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Название работы')),
                ('result', models.CharField(default='', max_length=300, null=True, verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Работы учеников',
                'verbose_name_plural': 'Работы учеников',
            },
        ),
        migrations.CreateModel(
            name='Puples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, null=True, verbose_name='Фамилия')),
                ('rate', models.PositiveIntegerField(default=0, verbose_name='Рейтинг ученика')),
                ('image', models.ImageField(blank=True, default='puples_photo/user-2.png', upload_to='puples_photo', verbose_name='Фотография профиля')),
                ('user', models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Связь с таблицей пользователей')),
            ],
            options={
                'verbose_name': 'Ученики',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата посещения')),
                ('name', models.CharField(max_length=200, verbose_name='Название мероприятия')),
                ('organization', models.CharField(max_length=300, verbose_name='Название организации')),
                ('check', models.BooleanField(default=False)),
                ('event_rate', models.PositiveIntegerField(default=1)),
                ('verification_file', models.FileField(null=True, upload_to='verification_files/', verbose_name='Файл')),
                ('events', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Puples', verbose_name='Мероприятия')),
            ],
            options={
                'verbose_name': 'Мероприятия',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
