# Generated by Django 3.0.6 on 2020-05-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puples',
            name='applicant_first_result',
            field=models.FloatField(blank=True, default=0, verbose_name='Результат первого этапа'),
        ),
        migrations.AddField(
            model_name='puples',
            name='applicant_progress',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (25, '25'), (50, '50'), (75, '75'), (100, '100')], default=0, verbose_name='Прогресс'),
        ),
        migrations.AddField(
            model_name='puples',
            name='status',
            field=models.CharField(choices=[('ST10', 'Ученик 10 ИТ-класса'), ('ST11', 'Ученик 11 ИТ-класса'), ('APP', 'Кандидат в ИТ-класс')], default='ST10', max_length=30, verbose_name='Статуc'),
        ),
    ]
