# Generated by Django 3.0.6 on 2020-07-11 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_applicantaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummerPractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Название курса')),
                ('description', models.CharField(default='', max_length=1000, verbose_name='Описание курса')),
                ('date', models.DateField(default='', verbose_name='Дата')),
                ('time', models.TimeField(default='', verbose_name='Время начала курса')),
                ('image', models.ImageField(blank=True, default='puples_photo/user-2.png', upload_to='logo_practice', verbose_name='Логотип курса')),
            ],
        ),
        migrations.AlterField(
            model_name='applicantaction',
            name='action_app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Puples', verbose_name='Кандидат'),
        ),
    ]
