# Generated by Django 3.0.6 on 2020-07-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200711_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='summerpractice',
            name='id_registers',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='ID учеников, кто дал правильный ответ'),
        ),
    ]
