# Generated by Django 3.0.1 on 2020-09-01 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_summerpractice_id_registers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('product_size', models.CharField(max_length=200, verbose_name='Размер или краткое описание товара')),
                ('product_photo', models.ImageField(blank=True, upload_to='products_photo/', verbose_name='Фотография товара')),
                ('remained_amount', models.PositiveIntegerField(verbose_name='Количество оставшегося товара')),
                ('price', models.PositiveIntegerField(verbose_name='Цена товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.AlterModelOptions(
            name='applicantaction',
            options={'verbose_name': 'Кандидаты', 'verbose_name_plural': 'Кандидаты'},
        ),
        migrations.AlterModelOptions(
            name='puples',
            options={'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='summerpractice',
            options={'verbose_name': 'Летняя практика', 'verbose_name_plural': 'Летняя практика'},
        ),
        migrations.AddField(
            model_name='puples',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='puples',
            name='phone',
            field=models.CharField(default='', max_length=12, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='puples',
            name='status',
            field=models.CharField(choices=[('ST10', 'Ученик 10 ИТ-класса'), ('ST11', 'Ученик 11 ИТ-класса'), ('APP', 'Кандидат в ИТ-класс'), ('TEACH', 'Учитель')], default='ST10', max_length=30, verbose_name='Статуc'),
        ),
        migrations.CreateModel(
            name='BoughtProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_date', models.DateField(auto_now_add=True, verbose_name='Дата покупки')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Puples', verbose_name='Покупатель товара')),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.MarketProduct', verbose_name='Ссылка на основной товар')),
            ],
        ),
    ]
