# Generated by Django 3.0.1 on 2020-09-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200901_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='boughtproduct',
            name='given',
            field=models.BooleanField(default=0, verbose_name='Выдан ли товар покупателю'),
        ),
    ]
