# Generated by Django 3.0.1 on 2020-09-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20200901_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketproduct',
            name='product_color',
            field=models.CharField(default='Не указан', max_length=200, verbose_name='Цвет товара'),
        ),
        migrations.AlterField(
            model_name='marketproduct',
            name='product_size',
            field=models.CharField(default='Стандарт', max_length=200, verbose_name='Размер товара'),
        ),
    ]
