# Generated by Django 3.0.1 on 2020-09-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20200901_2338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoughtProduct',
        ),
        migrations.DeleteModel(
            name='MarketProduct',
        ),
    ]
