# Generated by Django 3.0.1 on 2020-09-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boughtproduct',
            options={'verbose_name': 'Заказ/купленный товар', 'verbose_name_plural': 'Заказы и купленные товары'},
        ),
    ]
