# Generated by Django 3.0.1 on 2020-09-05 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20200902_1651'),
        ('market', '0002_auto_20200902_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='boughtproduct',
            name='connected_event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Events', verbose_name='Ссылка на Event с этой покупкой'),
        ),
    ]
