# Generated by Django 3.0.1 on 2020-09-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_boughtproduct_connected_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='boughtproduct',
            name='given_date',
            field=models.DateField(default=None, verbose_name='Дата выдачи товара'),
        ),
    ]
