# Generated by Django 3.0.1 on 2020-09-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20200905_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtproduct',
            name='given_date',
            field=models.DateField(verbose_name='Дата выдачи товара'),
        ),
    ]
