# Generated by Django 3.0.1 on 2020-09-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20200905_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtproduct',
            name='given_date',
            field=models.DateField(null=True, verbose_name='Дата выдачи товара'),
        ),
    ]
