# Generated by Django 3.0.4 on 2020-09-16 16:48

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Название задачи')),
                ('date', models.DateField(null=True, verbose_name='Дата задачи')),
                ('discription_task', tinymce.models.HTMLField(verbose_name='Условие задачи')),
                ('status_task', models.CharField(choices=[('ST10', 'Ученик 10 ИТ-класса'), ('ST11', 'Ученик 11 ИТ-класса'), ('TEACH', 'Учитель')], default='ST10', max_length=30, verbose_name='Выберите класс')),
                ('result', models.CharField(max_length=200, null=True, verbose_name='Результат')),
                ('count_answer', models.IntegerField(default=0, verbose_name='Количество человек, которые могут решить задачу')),
                ('id_puple_correct_answers', models.CharField(blank=True, default='', max_length=200, verbose_name='ID учеников, кто дал правильный ответ')),
            ],
            options={
                'verbose_name': 'Задача дня',
                'verbose_name_plural': 'Задача дня',
            },
        ),
    ]
