# Generated by Django 3.0.4 on 2020-09-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daytask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='score',
            field=models.IntegerField(default=5, verbose_name='Максимальный балл за задачу'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='count_answer',
            field=models.IntegerField(default=2, verbose_name='Количество человек, которые могут решить задачу'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='result',
            field=models.CharField(max_length=200, null=True, verbose_name='Ответ на задачу'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status_task',
            field=models.CharField(choices=[('ST10', 'Ученик 10 ИТ-класса'), ('ST11', 'Ученик 11 ИТ-класса')], default='ST10', max_length=30, verbose_name='Выберите класс'),
        ),
    ]
