# Generated by Django 3.0.1 on 2020-09-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daytask', '0003_tasks_tries'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='tries_list',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='ID учеников, совершившие попытку'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='tries',
            field=models.IntegerField(default=0, verbose_name='Количество попыток ответа на каждого ученика (0 - бесконечно)'),
        ),
    ]
